name: CI

on:
  push:
    branches: [ main, signals-based, simplified, pre-java8 ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '25' ]  # Try Java 25 first
      fail-fast: false

    name: Test with Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones disabled for SonarCloud analysis

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'oracle'  # Oracle should have Java 25 GA

    - name: Display Java version
      run: java -version

    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Run tests with coverage
      run: ./gradlew test jacocoTestReport --no-daemon

    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
      run: ./gradlew sonar --info

    # Test results are available in the build/test-results directory
    # Remove the test reporter that requires special permissions

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always() && github.event_name != 'pull_request'
      with:
        name: test-results-${{ matrix.java }}
        path: build/test-results/test/
        retention-days: 7

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always() && github.event_name != 'pull_request'
      with:
        name: coverage-reports-${{ matrix.java }}
        path: |
          build/reports/jacoco/test/html/
          build/reports/jacoco/test/jacocoTestReport.xml
        retention-days: 7

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success() && github.event_name != 'pull_request'
      with:
        name: build-artifacts-${{ matrix.java }}
        path: build/libs/
        retention-days: 7

  # Special job for the simplified branch which doesn't use Gradle
  test-simplified:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/simplified'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # Use stable version for simple example
        distribution: 'temurin'

    - name: Compile SimpleGameOfLife
      run: javac SimpleGameOfLife.java

    - name: Test SimpleGameOfLife compilation
      run: java SimpleGameOfLife &
      timeout-minutes: 1
      # Just test that it compiles and starts; kill after timeout

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # Use stable for analysis
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Run any linting or style checks if configured
    # - name: Run checkstyle
    #   run: ./gradlew checkstyleMain checkstyleTest --no-daemon

    # - name: Run SpotBugs
    #   run: ./gradlew spotbugsMain spotbugsTest --no-daemon

    - name: Check for dependency updates
      run: ./gradlew dependencyUpdates --no-daemon || true
      continue-on-error: true