name: Java 25 Multi-Platform

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM

permissions:
  contents: read
  checks: write
  actions: write

jobs:
  test-java25:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    name: Java 25 on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'oracle'  # Java 25 GA is now available

    - name: Check Java Version
      run: |
        java -version
        javac -version

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for gradlew
      if: runner.os != 'Windows'
      run: chmod +x gradlew

    - name: Build and Test
      run: ./gradlew build test --no-daemon --info

    - name: Report Results
      if: always()
      run: |
        echo "### Test Results for ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
        echo "Java version used:" >> $GITHUB_STEP_SUMMARY
        java -version 2>&1 | head -n 1 >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f build/test-results/test/*.xml ]; then
          echo "✅ Tests completed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Tests did not complete" >> $GITHUB_STEP_SUMMARY
        fi