name: Java 25 Experimental

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM

jobs:
  test-java25:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    name: Java 25 on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # Try to download and set up Java 25 manually
    - name: Download Java 25 EA (Linux)
      if: runner.os == 'Linux'
      run: |
        # Try to download Java 25 early access from OpenJDK or Oracle
        # This URL will need to be updated when Java 25 EA is available
        echo "Attempting to download Java 25 EA..."
        # wget https://download.java.net/java/early_access/jdk25/XX/GPL/openjdk-25-ea+XX_linux-x64_bin.tar.gz -O openjdk25.tar.gz || true
        # If download succeeds:
        # tar -xzf openjdk25.tar.gz
        # export JAVA_HOME=$PWD/jdk-25
        # export PATH=$JAVA_HOME/bin:$PATH
        echo "Java 25 EA not yet available, falling back to Java 21"

    # Fallback to the highest available Java
    - name: Set up Latest Available JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # Update when higher versions are available
        distribution: 'oracle'
        check-latest: true

    - name: Check Java Version
      run: |
        java -version
        javac -version

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for gradlew
      if: runner.os != 'Windows'
      run: chmod +x gradlew

    - name: Build and Test
      run: ./gradlew build test --no-daemon --info

    - name: Report Results
      if: always()
      run: |
        echo "### Test Results for ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
        echo "Java version used:" >> $GITHUB_STEP_SUMMARY
        java -version 2>&1 | head -n 1 >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f build/test-results/test/*.xml ]; then
          echo "✅ Tests completed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Tests did not complete" >> $GITHUB_STEP_SUMMARY
        fi